### ISSUE TITLE
Too many commits since last release

### ISSUE THREAD

**Issue by Iristallite** [Tylemagne/Gopher#102]
Please take this as an opportunity to compile a new build.

**Comment by stevedefazio** [comment]
I completely agree. Is there anything in particular that's preventing a new release? I love this tool, but I can see that the latest release was awhile ago. I'd happily lend a hand if necessary.

**Comment by Iristallite** [comment]
83 is just too many

**Comment by AlbertoBoc** [comment]
I hope you make a new release asap, too.

**Comment by BunnyTub** [comment]
As of 2020 there hasn't been any new releases as the project seems to be abandoned.

**Comment by achimmihca** [comment]
In #70 someone said that he is doing a maintained fork. You might want to try this "GopherRenewed".

Also, I just created a build with the more recent changes and parameters (e.g. DEAD_ZONE, SCROLL_SPEED, SWAP_THUMBSTICKS, CURSOR_SPEED) [over here](https://github.com/achimmihca/Gopher360/releases/tag/v1.0-achimmihca-fork).
